postgresql-gitlab:
  image: sameersbn/postgresql:9.4
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:7.10.2
  links:
    - redis-gitlab:redisio
    - postgresql-gitlab:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
redis-gitlab:
  image: sameersbn/redis:latest
  volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis
